POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1pa2tpIGhpaXJpIiwiaWQiOiI2NjgwMjc3NWI3M2I0OWQxZjQyMjZjMjciLCJpYXQiOjE3MTk2NzQ3ODcsImV4cCI6MTcxOTY3ODM4N30.eB7nYddqj-A7LBTMDPIPa8LoGIuItebo76LI65MmLo8

{
    "title": "Aku Ankka",
    "author": "Aku Ankan Tarinat",
    "url": "https://en.wikipedia.org/wiki/Aku_Ankka",
    "likes": 313
}