POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1pa2tpIGhpaXJpNSIsImlkIjoiNjY4MDMxMDE0YWZjODBmYjExYjNkNGY4IiwiaWF0IjoxNzE5Njc3MTkzLCJleHAiOjE3MTk2ODA3OTN9.o7ecrrMeDr1sl6d5XynWimdoPN0F-s2dafnaQAMZtXs

{
    "title": "Aku Ankka",
    "author": "Aku Ankan Tarinat",
    "url": "https://en.wikipedia.org/wiki/Aku_Ankka",
    "likes": 313
}