POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluQGdvb2dsZS5jb20iLCJpZCI6MSwiaWF0IjoxNzI0NzcyMjg2fQ.uRZaihJfrNn_LHf-1jHPJ3QTzQk3bY8dXM_aI2ViTcI

{
    "author": "new2 author",
    "url": "new2 url",
    "title": "new2 title",
    "year": 2012
}

