services:
  app:
    image: todo-frontend-dev
    build:
      context: ./todo-frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./todo-frontend:/usr/src/app
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_HOST=127.0.0.1
      - WATCHPACK_POLLING=true
      - VITE_BACKEND_URL=http://localhost:8080/api
    container_name: todo-frontend-dev

  backend:
    build:
      context: ./todo-backend
      dockerfile: Dockerfile
    command: npm run dev
    volumes:
      - ./todo-backend:/usr/src/app
    environment:
      - DEBUG=playground:*
      - REDIS_URL=redis://redis:6379
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:       
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js

  redis:
    image: redis
    command: ['redis-server', '--appendonly', 'yes'] 
    volumes: 
      - ./todo-backend/redis_data:/data

  nginx:
    image: nginx:1.25-alpine
    volumes:
      - ./nginx.dev.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - app
      - backend