DELETE http://localhost:3001/api/blogs/66803902b59d14708a3cf780
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpZCI6IjY2ODAzOGRkYjU5ZDE0NzA4YTNjZjc3YyIsImlhdCI6MTcxOTY3OTIxMywiZXhwIjoxNzE5NjgyODEzfQ.lNlgH0U7kBPlvrXLTa8x0bZdn_4UPrvTn56X9XSSBRk
