DELETE http://localhost:3001/api/blogs/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOjEsImlhdCI6MTcyNDY3NDg5Nn0.8JuUsdWGYxNdTDbT4V7DYJBn-2Y9UJ-yZYu6a6UIJ90
